# Generated by Django 3.1.1 on 2020-10-20 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.TextField(default='', unique=True)),
                ('person_age', models.IntegerField(default='')),
                ('person_gender', models.TextField(default='')),
                ('person_account', models.TextField(default='')),
                ('person_password', models.TextField(default='')),
                ('person_authority', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(default='', unique=True)),
                ('item_content', models.TextField(default='')),
                ('item_introduction', models.TextField(default='')),
                ('item_date', models.DateTimeField(default='')),
                ('item_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newfirst.personnel')),
            ],
        ),
    ]
