# Generated by Django 3.1.1 on 2020-10-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField(default='')),
                ('type', models.TextField(default='')),
                ('name', models.TextField(default='', unique=True)),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DesignCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', unique=True)),
                ('content', models.TextField(default='')),
                ('group', models.TextField(default='')),
                ('type', models.TextField(default='')),
            ],
        ),
    ]
