# Generated by Django 3.1.1 on 2020-10-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0002_analysisrules_designcriteria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisrules',
            old_name='content',
            new_name='describe',
        ),
        migrations.RenameField(
            model_name='analysisrules',
            old_name='group',
            new_name='remark',
        ),
        migrations.RenameField(
            model_name='designcriteria',
            old_name='content',
            new_name='describe',
        ),
        migrations.RenameField(
            model_name='designcriteria',
            old_name='group',
            new_name='remark',
        ),
    ]
