# Generated by Django 3.1.1 on 2020-10-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0004_scenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_leader',
        ),
    ]
