# Generated by Django 3.1.1 on 2020-10-23 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0005_auto_20201024_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(default='')),
                ('type', models.TextField(default='')),
                ('name', models.TextField(default='', unique=True)),
                ('describe', models.TextField(default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newfirst.item')),
            ],
        ),
    ]
