# Generated by Django 3.1.1 on 2020-10-24 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0006_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_element', models.TextField(default='')),
                ('case_name', models.TextField(default='', unique=True)),
                ('case_content', models.TextField(default='')),
                ('case_describe', models.TextField(default='')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newfirst.rules')),
            ],
        ),
    ]
