# Generated by Django 3.1.1 on 2020-10-24 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0008_case_verify_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fmea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improve', models.TextField(default='')),
                ('reason', models.TextField(default='')),
                ('local_influence', models.TextField(default='')),
                ('upper_influence', models.TextField(default='')),
                ('system_influence', models.TextField(default='')),
                ('influence_level', models.TextField(default='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newfirst.case')),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.TextField(default='')),
                ('fmea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newfirst.fmea')),
            ],
        ),
    ]
