# Generated by Django 3.1.1 on 2020-10-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0009_demand_fmea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='demand',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmea',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newfirst.case', unique=True),
        ),
        migrations.AlterField(
            model_name='fmea',
            name='improve',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmea',
            name='influence_level',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmea',
            name='local_influence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmea',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmea',
            name='system_influence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmea',
            name='upper_influence',
            field=models.TextField(blank=True, default=''),
        ),
    ]
