# Generated by Django 3.1.1 on 2020-10-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0010_auto_20201024_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmea',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newfirst.case'),
        ),
    ]
