# Generated by Django 3.1.1 on 2020-10-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0012_auto_20201025_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designcriteria',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
