# Generated by Django 3.1.1 on 2020-10-31 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0015_auto_20201031_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenes',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newfirst.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scenes',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
