# Generated by Django 3.1.1 on 2020-10-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0018_fmea_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmea',
            name='ignore',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
