# Generated by Django 3.1.1 on 2020-10-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0020_design_belong'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='verify_count',
            field=models.IntegerField(default=0),
        ),
    ]
