# Generated by Django 3.1.1 on 2020-11-01 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0021_case_verify_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmea',
            name='case',
        ),
        migrations.AddField(
            model_name='case',
            name='last_verify_result',
            field=models.TextField(default='未检验'),
        ),
        migrations.AddField(
            model_name='fmea',
            name='case_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fmea',
            name='case_describe',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fmea',
            name='case_element',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fmea',
            name='case_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fmea',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newfirst.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='verify_result',
            field=models.TextField(default='未检验'),
        ),
    ]
