# Generated by Django 3.1.1 on 2020-11-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0022_auto_20201101_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='person_name',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='person_age',
            new_name='authority',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='person_account',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='person_authority',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='person_gender',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='person_password',
        ),
        migrations.AddField(
            model_name='personnel',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='personnel',
            name='gender',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='personnel',
            name='name',
            field=models.TextField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='team',
            field=models.TextField(blank=True, default=''),
        ),
    ]
