# Generated by Django 3.1.1 on 2020-11-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newfirst', '0024_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default='')),
                ('path', models.TextField(default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newfirst.item')),
            ],
        ),
    ]
