# Generated by Django 3.1 on 2020-09-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invalid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invalid_name', models.TextField(default='', unique=True)),
                ('invalid_content', models.TextField(default='')),
                ('invalid_details', models.TextField(default='')),
                ('invalid_describe', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='InvalidVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_result', models.BooleanField()),
                ('invalid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.invalid')),
            ],
        ),
    ]
