# Generated by Django 3.1 on 2020-09-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_invalid_invalidverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalid',
            name='invalid_verify',
            field=models.TextField(default='null'),
        ),
        migrations.DeleteModel(
            name='InvalidVerify',
        ),
    ]
