# Generated by Django 3.1.1 on 2020-10-13 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_auto_20200911_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(default='', unique=True)),
                ('item_content', models.TextField(default='')),
                ('item_describe', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='invalid',
            name='invalid_type',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='ItemTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_describe', models.TextField(default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.item')),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.trace')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInvalid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_describe', models.TextField(default='')),
                ('invalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.invalid')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.item')),
            ],
        ),
    ]
